#!/usr/bin/env python3
"""
RSVP torsion-driven flow field
--------------------------------
Flow is generated by vorticity gradients and damped by
explicit vorticity suppression (torsion regularization).
"""

import numpy as np

# ---------- finite differences (periodic) ----------

def roll(a, s, ax): return np.roll(a, s, axis=ax)

def grad_x(f, dx): return (roll(f, -1, 1) - roll(f, 1, 1)) / (2*dx)
def grad_y(f, dy): return (roll(f, -1, 0) - roll(f, 1, 0)) / (2*dy)

def laplacian(f, dx, dy):
    return ((roll(f,-1,1) - 2*f + roll(f,1,1))/(dx*dx)
          + (roll(f,-1,0) - 2*f + roll(f,1,0))/(dy*dy))

def advect(f, vx, vy, dx, dy):
    fx = np.where(vx >= 0, (f - roll(f,1,1))/dx,
                           (roll(f,-1,1)-f)/dx)
    fy = np.where(vy >= 0, (f - roll(f,1,0))/dy,
                           (roll(f,-1,0)-f)/dy)
    return -(vx*fx + vy*fy)

def curl_z(vx, vy, dx, dy):
    return grad_x(vy, dx) - grad_y(vx, dy)

def perp_grad(f, dx, dy):
    return -grad_y(f, dy), grad_x(f, dx)

# ---------- torsion flow step ----------

def step_flow(vx, vy, Phi, S, dx, dy, p):
    """
    v_t = torsion_drive - vorticity_penalty - damping + viscosity
    """
    ω = curl_z(vx, vy, dx, dy)

    # torsion drive: ∇⊥ω
    tx, ty = perp_grad(ω, dx, dy)

    # vorticity suppression (penalize large ω)
    pen_x = grad_x(ω**2, dx)
    pen_y = grad_y(ω**2, dy)

    advvx = advect(vx, vx, vy, dx, dy)
    advvy = advect(vy, vx, vy, dx, dy)

    dvx = (
        advvx
        + p["lambda"] * tx
        - p["gamma"] * pen_x
        - p["nu"] * vx
        + p["kv"] * laplacian(vx, dx, dy)
    )

    dvy = (
        advvy
        + p["lambda"] * ty
        - p["gamma"] * pen_y
        - p["nu"] * vy
        + p["kv"] * laplacian(vy, dx, dy)
    )

    return vx + p["dt"]*dvx, vy + p["dt"]*dvy