"""
Finite characterization computation on the twelve-state system.

Question: do the monotonicity constraints (M) generated by the system's
admissibility endomorphisms force every solution Phi to factor through E,
or do bracket-sensitive invariants survive?

Method:
1. Enumerate all admissibility endomorphisms F. Cost-nonincrease bounds
   generator images: F_*(a) is a word of cost <= 1 (empty or 'a');
   F_*(b) a word of cost <= 2 (empty, 'a', 'b', 'aa'). Intertwining plus
   reachability of every state from (0,0) means F is determined by
   (F(0,0), F_*(a), F_*(b)) when consistent: 12*2*4 = 96 candidates.
2. Identify the E-sufficient endomorphisms (E preserved on all pairs).
3. Build the constraint digraph on ordered state pairs:
   Phi(F(C),F(C')) <= Phi(C,C') for every F; equality when F sufficient.
4. Compute SCCs (forced equalities) and the induced DAG (forced order).
5. Compare the SCC partition with the level sets of E.
"""

import math, itertools
from collections import defaultdict

L, P = 3, 4
states = [(l, p) for l in range(L) for p in range(P)]

def op_a(s): l, p = s; return (l, (p + 1) % P)
def op_b(s): l, p = s; return (l + 1, p) if l < L - 1 else (l, 0)
OP = {"a": op_a, "b": op_b}

def apply_word(word, s):
    for w in word:
        s = OP[w](s)
    return s

# ---- E via Dijkstra (unit graph small enough for BFS on weighted edges) ----
import heapq
def dijkstra(src):
    dist = {s: math.inf for s in states}; dist[src] = 0.0
    pq = [(0.0, src)]
    while pq:
        d, s = heapq.heappop(pq)
        if d > dist[s]: continue
        for name, c in (("a", 1.0), ("b", 2.0)):
            t = OP[name](s)
            if d + c < dist[t]:
                dist[t] = d + c; heapq.heappush(pq, (d + c, t))
    return dist
E = {s: dijkstra(s) for s in states}

# ---- 1. Enumerate admissibility endomorphisms ----
WA = [(), ("a",)]                       # cost 0, 1  <= c(a)=1
WB = [(), ("a",), ("b",), ("a", "a")]   # cost 0,1,2,2 <= c(b)=2

def build_F(s0, wa, wb):
    F = {(0, 0): s0}
    frontier = [(0, 0)]
    while frontier:
        C = frontier.pop()
        for gen, w in (("a", wa), ("b", wb)):
            Cn = OP[gen](C)
            tgt = apply_word(w, F[C])
            if Cn in F:
                if F[Cn] != tgt:
                    return None
            else:
                F[Cn] = tgt
                frontier.append(Cn)
    if len(F) != len(states):
        return None
    # verify intertwining on ALL states (loop closure)
    for C in states:
        if F[op_a(C)] != apply_word(wa, F[C]): return None
        if F[op_b(C)] != apply_word(wb, F[C]): return None
    return F

endos = []
for s0 in states:
    for wa in WA:
        for wb in WB:
            F = build_F(s0, wa, wb)
            if F is not None:
                endos.append((s0, wa, wb, F))

print(f"admissibility endomorphisms found: {len(endos)}")
for s0, wa, wb, F in endos:
    img = len(set(F.values()))
    print(f"  F(0,0)={s0}  F*(a)={''.join(wa) or 'id'}  F*(b)={''.join(wb) or 'id'}  |image|={img}")

# ---- 2. E-sufficiency ----
def sufficient(F):
    for C in states:
        for Cp in states:
            e1, e2 = E[C][Cp], E[F[C]][F[Cp]]
            if not (e1 == e2 or (math.isinf(e1) and math.isinf(e2))):
                return False
    return True

suff = [x for x in endos if sufficient(x[3])]
print(f"\nE-sufficient endomorphisms: {len(suff)}")
for s0, wa, wb, F in suff:
    print(f"  F(0,0)={s0}  F*(a)={''.join(wa) or 'id'}  F*(b)={''.join(wb) or 'id'}")

# ---- 3-4. Constraint digraph on ordered pairs, SCCs, forced order ----
pairs = [(C, Cp) for C in states for Cp in states if C != Cp]
pidx = {p: i for i, p in enumerate(pairs)}
n = len(pairs)
adj = defaultdict(set)   # edge u -> v meaning Phi(v) <= Phi(u)

for s0, wa, wb, F in endos:
    suf = sufficient(F)
    for (C, Cp) in pairs:
        img = (F[C], F[Cp])
        if img[0] == img[1]:
            continue  # Phi on diagonal is 0; gives Phi>=0, vacuous
        u, v = pidx[(C, Cp)], pidx[img]
        adj[u].add(v)
        if suf:
            adj[v].add(u)

# Tarjan SCC (iterative)
index_counter = [0]; stack = []; low = {}; num = {}; on = {}; comp = {}; ncomp = [0]
def scc():
    for root in range(n):
        if root in num: continue
        work = [(root, iter(sorted(adj[root])))]
        num[root] = low[root] = index_counter[0]; index_counter[0] += 1
        stack.append(root); on[root] = True
        while work:
            node, it = work[-1]
            advanced = False
            for w in it:
                if w not in num:
                    num[w] = low[w] = index_counter[0]; index_counter[0] += 1
                    stack.append(w); on[w] = True
                    work.append((w, iter(sorted(adj[w]))))
                    advanced = True
                    break
                elif on.get(w):
                    low[node] = min(low[node], num[w])
            if advanced: continue
            work.pop()
            if work:
                low[work[-1][0]] = min(low[work[-1][0]], low[node])
            if low[node] == num[node]:
                while True:
                    w = stack.pop(); on[w] = False
                    comp[w] = ncomp[0]
                    if w == node: break
                ncomp[0] += 1
scc()
print(f"\nordered pairs: {n}, forced-equality classes (SCCs): {ncomp[0]}")

# ---- 5. Compare with E level sets ----
elevels = defaultdict(set)
for p in pairs:
    e = E[p[0]][p[1]]
    elevels[e].add(comp[pidx[p]])
print("\nE-level  ->  number of distinct SCCs inside that level set:")
for e in sorted(elevels, key=lambda x: (math.isinf(x), x)):
    print(f"  E={e if math.isfinite(e) else 'inf':>4}: {len(elevels[e])} classes, "
          f"{sum(1 for p in pairs if E[p[0]][p[1]]==e or (math.isinf(e) and math.isinf(E[p[0]][p[1]]))) if not math.isinf(e) else sum(1 for p in pairs if math.isinf(E[p[0]][p[1]]))} pairs")

# does any SCC mix different E levels? (would forbid injective f)
mix = defaultdict(set)
for p in pairs:
    mix[comp[pidx[p]]].add(E[p[0]][p[1]])
mixed = {c: v for c, v in mix.items() if len(v) > 1}
print(f"\nSCCs mixing different E-values: {len(mixed)}")
for c, v in list(mixed.items())[:5]:
    members = [p for p in pairs if comp[pidx[p]] == c][:4]
    print(f"  class {c}: E-values {sorted(v, key=lambda x:(math.isinf(x),x))}, e.g. {members}")

# ---- Is a non-E-factoring monotone Phi possible? ----
# Condition: exist two pairs with SAME E value in DIFFERENT SCCs such that
# no forced order chain requires their equality; then assign them different
# values consistently with the DAG via a linear extension.
# We test constructively: longest-path levels in the condensation DAG.
cadj = defaultdict(set)
for u in range(n):
    for v in adj[u]:
        if comp[u] != comp[v]:
            cadj[comp[u]].add(comp[v])
# Phi must be <= along edges; take Phi = (length of longest outgoing chain)
import functools
import sys
sys.setrecursionlimit(10000)
@functools.lru_cache(maxsize=None)
def depth(c):
    return 1 + max((depth(d) for d in cadj[c]), default=0)
phi_new = {p: depth(comp[pidx[p]]) for p in pairs}

# verify monotonicity of phi_new under all endos, equality under sufficient
ok = True
for s0, wa, wb, F in endos:
    suf = sufficient(F)
    for (C, Cp) in pairs:
        img = (F[C], F[Cp])
        if img[0] == img[1]: continue
        a1, a2 = phi_new[(C, Cp)], phi_new[img]
        if a2 > a1: ok = False
        if suf and a2 != a1: ok = False
print(f"\nconstructed chain-depth functional satisfies (M)+(I) on endos: {ok}")

# does it factor through E?
byE = defaultdict(set)
for p in pairs:
    byE[E[p[0]][p[1]]].add(phi_new[p])
nonfactor = {e: v for e, v in byE.items() if len(v) > 1}
print(f"E-levels on which chain-depth functional takes multiple values: {len(nonfactor)}")
for e, v in sorted(nonfactor.items(), key=lambda kv:(math.isinf(kv[0]),kv[0]))[:8]:
    ex = {}
    for p in pairs:
        ee = E[p[0]][p[1]]
        if (ee == e or (math.isinf(e) and math.isinf(ee))) and phi_new[p] not in ex:
            ex[phi_new[p]] = p
    print(f"  E={e}: values {sorted(v)}  witnesses {ex}")
